### ISSUE TITLE
TLS/SSL: Allow to specify additional CAs

### ISSUE THREAD

**Issue by senpro-ingwersenk** [narrowlink/narrowlink#111]
**Is your feature request related to a problem? Please describe.**
At my work environment, our firewall oversees HTTPS traffic by using a self-signed certificate as an additional CA. So, I can not connect to my gateway, because the cert returned from a HTTP request is not my usual Let's Encrypt certificate:
```
> ./narrowlink.exe list
2024-06-18T08:25:36.106717Z ERROR narrowlink::manage: Unable to connect to the gateway: IO Error: invalid peer certificate: UnknownIssuer
2024-06-18T08:25:36.106830Z  INFO narrowlink::manage: Try again
2024-06-18T08:25:36.184497Z ERROR narrowlink::manage: Unable to connect to the gateway: IO Error: invalid peer certificate: UnknownIssuer
2024-06-18T08:25:36.184516Z  INFO narrowlink::manage: Try again in 5 secs
...
```

**Describe the solution you'd like**
Most HTTP clients allow to either specify additional CAs to load in, or alternatives. I would like to see that exposed as an option in the configuration for agents and clients.

**Describe alternatives you've considered**
The OS - be it Windows or Linux - will provide a global CA bundle. Technically, the required cert is indeed in my SSL Store on Windows - I am a little surprised it wasn't used.

**Additional context**
Got none. :)

Kind regards!

**Comment by SajjadPourali** [comment]
Hello,

Narrowlink automatically issues and renews certificates for your domains, so you do not need to upload your self-signed certificate. It does not use the system certificate chain, which is why you can't use your own certificate even if you have imported them. I assume that you did not set a domain on your server. In this case, you can switch to the [WS protocol](https://narrowlink.com/docs/gateway#configuration), which does not use the TLS protocol, so you do not need the certificate, which may be suitable for your test (although insecure).

I am considering adding this feature, but I am hesitating between using the OS certificate root store or adding a new configuration option to add individual self-signed certificates.

**Comment by senpro-ingwersenk** [comment]
> Narrowlink automatically issues and renews certificates for your domains

Yes - when using `!Wss`, which I did not, on purpose:
```yaml
name: birb-it-narrowlink
secret: <snip>
services:
- !Ws
  listen_addr: "127.0.0.1:8998"
  domains: ["nl.birb.it"]
```

And, in my Caddy setup, I just do this:
```
nl.birb.it {
  reverse_proxy * localhost:8998
}
```

Reason being that I provision my certs via DNS-01 challenge instead of HTTP-01 or ALPN-01; the reason is a little complicated but that is why I use Caddy as a reverse proxy. Thus, the certificate is very much valid, configured, and set. :)

> It does not use the system certificate chain, which is why you can't use your own certificate even if you have imported them.

Any particular reason for that? Because that would mean it will always reject the corporate local CA no matter what - which is a problem...

> I am considering adding this feature, but I am hesitating between using the OS certificate root store or adding a new configuration option to add individual self-signed certificates.

Please use the OS store. We distribute the CA through GPOs; it is very common to do so, at least on Windows.

Thanks and kind regards!

**Comment by SajjadPourali** [comment]
I see. There is not plan to add the DNS-01 challenge very soon as it requires integration with an external API.


> Any particular reason for that? Because that would mean it will always reject the corporate local CA no matter what - which is a problem...

Due to the complexity of implementation in the past, I decided against it. However, I have checked and found that the rustls library now provides features that make it easier to implement. Therefore, I’ll add this feature to use the system root certificate, with an optional configuration to disable it.

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/116

**Comment by senpro-ingwersenk** [comment]
I went and tried out the recent 0.2.6 release and downloaded the binary off of the Github Release page just to make sure I really had the recent version. Oddly, however:

```
> $env:RUST_LOG="debug"
> ../../.cargo/bin/narrowlink-client.exe list
2024-09-04T06:55:44.790986Z DEBUG narrowlink_network::transport: using rustls to connect to 49.13.8.103:443
2024-09-04T06:55:45.049244Z ERROR narrowlink::manage: Unable to connect to the gateway: IO Error: invalid peer certificate: UnknownIssuer
2024-09-04T06:55:45.049280Z  INFO narrowlink::manage: Try again
2024-09-04T06:55:45.101184Z DEBUG narrowlink_network::transport: using rustls to connect to 49.13.8.103:443
2024-09-04T06:55:45.180106Z ERROR narrowlink::manage: Unable to connect to the gateway: IO Error: invalid peer certificate: UnknownIssuer
2024-09-04T06:55:45.180119Z  INFO narrowlink::manage: Try again in 5 secs
2024-09-04T06:55:50.201259Z DEBUG narrowlink_network::transport: using rustls to connect to 49.13.8.103:443
2024-09-04T06:55:50.244794Z ERROR narrowlink::manage: Unable to connect to the gateway: IO Error: invalid peer certificate: UnknownIssuer
2024-09-04T06:55:50.244814Z  INFO narrowlink::manage: Try again in 10 secs
```

Tracking the error message, I land here: https://github.com/narrowlink/narrowlink/blob/7bf894e531d5033c569877c6787ec4df622d9d5c/network/src/transport.rs#L40

But this correctly uses the rusttls platform verifier - and I double-checked, the root CA of our firewall really is installed and present. My browser can use it just fine.

Do you happen to know how I can debug this? This is not a narrowlink issue - but a rusttls one.

**Comment by senpro-ingwersenk** [comment]
After more digging, I found this: https://learn.microsoft.com/en-us/troubleshoot/windows-server/certificates-and-public-key-infrastructure-pki/valid-root-ca-certificates-untrusted

...and I followed some instructions I found for validating the certificate using `certutil` - which works, flawlessly so.

Since there are two stores (local user and system), which one does the verifier actually use?
