### ISSUE TITLE
Commit Cargo.lock to github

### ISSUE THREAD

**Issue by alx-alexpark** [narrowlink/narrowlink#13]
It is helpful to people packaging Narrowlink for different distributions if you could remove Cargo.lock from your .gitignore and commit it to git.

https://github.com/NixOS/nixpkgs/pull/248723#discussion_r1296498976

**Comment by SajjadPourali** [comment]
Sounds good! Feel free to create the PR.

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/commit/37def5c5cfd62a4d623d92fdf03d4e8d3eac0e08 Done
