### ISSUE TITLE
Fake VPN Implementation

### ISSUE THREAD

**Issue by SajjadPourali** [narrowlink/narrowlink#55]
Implement a fake VPN client to forward all traffic from the client to the agent. The VPN client must be unidirectional, allowing the client to see the agent and its network using a tun interface, while the agent doesn't have any tun interface or access to the client's network.

**Comment by 9to1url** [comment]
Cool, let me test :-)

**Comment by SajjadPourali** [comment]
> Cool, let me test :-)

It has not been implemented yet. Unlike other solutions, it involves handling raw packets at the user level due to the unique requirements mentioned in the initial post. This, in turn, requires tasks like TCP parsing and congestion control, which are quite challenging. I am actively working on it and can confirm that it will be added soon.

**Comment by SajjadPourali** [comment]
https://github.com/smoltcp-rs/smoltcp/pull/814
https://github.com/smoltcp-rs/smoltcp/issues/809

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/60

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/60
