### ISSUE TITLE
Transition from the lwip crate to a native alternative

### ISSUE THREAD

**Issue by SajjadPourali** [narrowlink/narrowlink#64]
LwIP is used as a TCP stack for TUN functionality. I've noticed that this library works; however, it is not suitable for Narrowlink in the long term due to three main problems:
1) it's difficult to handle large packets (which causes issues when integrating with WinTun)
2) troubleshooting difficulties
3) overhead

**Comment by SajjadPourali** [comment]
smoltcp might be a good option if the following pull request get merged.

https://github.com/smoltcp-rs/smoltcp/pull/814
https://github.com/smoltcp-rs/smoltcp/issues/809

**Comment by SajjadPourali** [comment]
smoltcp might be a good option if the following pull request get merged.

https://github.com/smoltcp-rs/smoltcp/pull/814
https://github.com/smoltcp-rs/smoltcp/issues/809

**Comment by 9to1url** [comment]
Great, I am also posted question related to lwIP in another thread.

**Comment by SajjadPourali** [comment]
https://crates.io/crates/ipstack

**Comment by 9to1url** [comment]
Cool 😎

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/73

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/73
