### ISSUE TITLE
Windows support for client's tun feature 

### ISSUE THREAD

**Issue by SajjadPourali** [narrowlink/narrowlink#65]
https://github.com/narrowlink/narrowlink/issues/64

**Comment by 9to1url** [comment]
Please advise if Tun already fully working on Linux and MacOS. :-)

**Comment by SajjadPourali** [comment]
"It is available for both Linux and macOS and should work smoothly. Please run `narrowlink t -h` to see the arguments:

```bash
Create a TUN tunnel

Usage:
  narrowlink tun [OPTIONS]

Description:
  Creates a TUN interface to connect to a remote endpoint
   ***           For testing purposes only           ***

Examples:
  narrowlink tun -n <agent name>
  narrowlink t -gdn <agent name> -k <key>

Options:
  -g, --gateway     Use as default gateway
  -d, --direct      Direct connection to the remote endpoint (peer-to-peer)
  -r, --relay       Relay connection to the remote endpoint (peer-to-gateway-to-peer)
  -n, --name=       The name of the agent (required)
  -k, --key=        The secret key for end-to-end encryption
  -l, --local=      The local address to bind to
  -m, --map=        The target address to connect to
```

For Windows support, there are two main problems:

1) I need to use Wintun, and its default MTU is 2^16, which LWIP cannot handle. However, I can decrease the MTU after initializing the TUN interface, but it's not effective, and I don't want to touch Windows network configs.

2) There is only one asynchronous implementation of a TUN interface in Windows with Rust, which looks improperly designed and has many performance issues (https://github.com/meh/rust-tun/pull/70) (at least my experience). There is another library that does not support async.

I expect to replace LWIP with my own created TCP/IP stack to address the first issue for the `0.2.0` release and postpone fixing the Windows problem for the future.

Please note that `-m` arg behavior is going to change.

**Comment by SajjadPourali** [comment]
> Your replacement for lwIP working on Windows or not?

I still haven't checked it; however, there is no platform dependency on it and can manage large mtu. I only checked Linux and macOS, which works.

**Comment by SajjadPourali** [comment]
> Your replacement for lwIP working on Windows or not?

https://github.com/SajjadPourali/ipstack/commit/83d6f83503b086792a39ca18098b7ca683d251d6

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/narrowlink/pull/73
