### ISSUE TITLE
Add license info to the binaries help

### ISSUE THREAD

**Issue by SajjadPourali** [narrowlink/narrowlink#70]

**Comment by 9to1url** [comment]
What's the Todo list for this? I might want to do it if I am capable 😁

**Comment by SajjadPourali** [comment]
> What's the Todo list for this? I might want to do it if I am capable 😁

Thank you. I would like to invite you to contribute to the creation of the [man](https://en.wikipedia.org/wiki/Man_page)(1) pages https://github.com/narrowlink/narrowlink/issues/71 based on the documentations, which are more necessary. After that, we can focus on adding the license to the binaries.
